filters:
  - label: âš™ feat
    regexs:
      - /feat/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸ› ï¸ fix
    regexs:
      - /fix/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸ’» style
    regexs:
      - /style/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸš€ chore
    regexs:
      - /chore/i
    events: [issues, pull_request]
    targets: [title]
